### Запрос на создание пользователя
POST http://localhost:8080/tasks
Content-type: application/json

{
  "title": "number 1",
  "description": "description 1"
}

### Запрос на создание пользователя
GET http://localhost:8080/tasks
Content-type: application/json

{
  "title": "number 1",
  "description": "description 1"
}

### Запрос на создание пользователя
DELETE http://localhost:8080/tasks
Content-type: application/json

{
  "title": "number 1",
  "description": "description 1"
}

### Запрос на создание пользователя
PUT http://localhost:8080/tasks
Content-type: application/json

{
  "title": "number 1",
  "description": "description 1"
}